import test from 'node:test';
import assert from 'node:assert/strict';
import { MemoryProfileRepository } from '../repository.ts';
import { ProfileService } from '../service.ts';
import { createProfileCapabilities } from '../capabilities.ts';
const ctx=(ownerId='u1')=>({ownerId,requestId:'r1',operationKey:'op-'+ownerId});
const cmd=(payload:any,owner='u1')=>({context:ctx(owner),payload,idempotencyKey:'k-'+Math.random()});
function setup(){const repo=new MemoryProfileRepository();return {repo,service:new ProfileService(repo)}}
test('保存并读取画像事实与目标方向',async()=>{const {service}=setup();await service.saveProfileFact(cmd({factType:'major',value:{text:'计算机科学'},source:'user_input'}));await service.updateUserGoal(cmd({direction:'前端开发'}));const p=await service.getUserProfile(ctx(),{});assert.equal((p.facts[0].value as any).text,'计算机科学');assert.equal(p.goals[0].value.direction,'前端开发')});
test('用户数据隔离',async()=>{const {service}=setup();await service.saveProfileFact(cmd({factType:'school',value:{text:'甲大学'},source:'user_input'}));const p=await service.getUserProfile(ctx('u2'),{});assert.equal(p.facts.length,0)});
test('完善度按九项字段计算',async()=>{const {service}=setup();const r=await service.getProfileCompletion(ctx(),{includeMissingFields:true});assert.equal(r.percentage,0);assert.equal(r.missingFields.length,9);assert.equal(r.ruleVersion,'profile-completion-v1')});
test('版本冲突拒绝过期写入',async()=>{const {service}=setup();await service.saveProfileFact(cmd({factType:'grade',value:{text:'大一'},source:'user_input'}));const r=await service.saveProfileFact({...cmd({factType:'grade',value:{text:'大二'},source:'user_input'}),expectedVersion:99});assert.equal(r.ok,false);assert.equal(r.error?.code,'VERSION_CONFLICT')});
test('四个 Agent Tool 均委托 Service',async()=>{const calls:string[]=[];const fake:any={getUserProfile:async()=>{calls.push('get_user_profile');return {}},getProfileCompletion:async()=>{calls.push('get_profile_completion');return {}},saveProfileFact:async()=>{calls.push('save_profile_fact');return {}},updateUserGoal:async()=>{calls.push('update_user_goal');return {}}};const tools=createProfileCapabilities(fake);for(const t of tools)await t.execute(ctx(),t.name==='update_user_goal'?{direction:'后端'}:t.name==='save_profile_fact'?{factType:'major',value:{text:'CS'},source:'user_input'}:{});assert.deepEqual(calls,['get_user_profile','get_profile_completion','save_profile_fact','update_user_goal'])});
test('写入 Tool 传递可信命令上下文和幂等键',async()=>{let received:any;const fake:any={getUserProfile:async()=>null,getProfileCompletion:async()=>({}),saveProfileFact:async(c:any)=>{received=c;return {ok:true,changed:true,domain:'profile',status:'applied',summary:'ok'}},updateUserGoal:async()=>({})};const tool=createProfileCapabilities(fake).find(t=>t.name==='save_profile_fact')!;await tool.execute(ctx(),{factType:'major',value:{text:'CS'},source:'user_input'});assert.equal(received.context.ownerId,'u1');assert.equal(received.context.operationKey,'op-u1');assert.equal(received.idempotencyKey,'op-u1');assert.equal(received.payload.factType,'major')});
test('测评来源必须带证据引用',async()=>{const {service}=setup();const r=await service.saveProfileFact(cmd({factType:'major',value:{text:'CS'},source:'assessment'}));assert.equal(r.error?.code,'INVALID_ARGUMENT')});
test('测评来源仅允许当前基础',async()=>{const {service}=setup();const r=await service.saveProfileFact(cmd({factType:'major',value:{text:'CS'},source:'assessment',evidenceRef:{evidenceId:'e1',evaluatedAt:'2026-09-14T00:00:00Z'}}));assert.equal(r.error?.code,'INVALID_ARGUMENT')});
test('每周时间不允许为负数',async()=>{const {service}=setup();const r=await service.saveProfileFact(cmd({factType:'weekly_time',value:{hours:-1},source:'user_input'}));assert.equal(r.error?.code,'INVALID_ARGUMENT')});
test('分区查询与完整画像计算分离',async()=>{const {service}=setup();await service.saveProfileFact(cmd({factType:'major',value:{text:'CS'},source:'user_input'}));await service.saveProfileFact(cmd({factType:'school',value:{text:'甲大学'},source:'user_input'}));const p=await service.getUserProfile(ctx(),{sections:['identity']});assert.equal(p.facts.length,2);assert.equal(p.missingFields.length,7)});
test('完善度可隐藏缺失字段',async()=>{const {service}=setup();const r=await service.getProfileCompletion(ctx(),{includeMissingFields:false});assert.equal(r.missingFields.length,0)});
test('目标方向版本冲突',async()=>{const {service}=setup();await service.updateUserGoal(cmd({direction:'前端'}));const r=await service.updateUserGoal({...cmd({direction:'后端'}),expectedVersion:9});assert.equal(r.error?.code,'VERSION_CONFLICT')});
test('相同事实重复提交不递增版本',async()=>{const {service}=setup();const first=await service.saveProfileFact(cmd({factType:'major',value:{text:'CS'},source:'user_input'}));const second=await service.saveProfileFact({...cmd({factType:'major',value:{text:'CS'},source:'user_input'}),expectedVersion:1});assert.equal(first.version,1);assert.equal(second.changed,false);assert.equal(second.version,1)});
test('相同目标重复提交不递增版本',async()=>{const {service}=setup();const first=await service.updateUserGoal(cmd({direction:'前端'}));const second=await service.updateUserGoal({...cmd({direction:'前端'}),expectedVersion:1});assert.equal(first.version,1);assert.equal(second.changed,false);assert.equal(second.version,1)});

