import type { Pool } from "pg";
import type { CareerRepository } from "./repository.ts";
import type { CareerPlan, JobGapAnalysis, TargetJob } from "./contracts.ts";
export class PostgresCareerRepository implements CareerRepository {
  private readonly pool: Pool;
  constructor(pool: Pool) { this.pool = pool; }
  async getPlan(ownerId: string, status?: CareerPlan["status"]) { const result = await this.pool.query<CareerPlan>(`SELECT id,owner_id AS "ownerId",status,version,direction_codes AS "directionCodes",target_job_id AS "targetJobId",target_company_name AS "targetCompanyName",target_city AS "targetCity",target_salary_text AS "targetSalaryText",rationale,updated_at::text AS "updatedAt" FROM career_plans WHERE owner_id=$1 AND ($2::text IS NULL OR status=$2) ORDER BY updated_at DESC LIMIT 1`, [ownerId, status ?? null]); return result.rows[0] ?? null; }
  async savePlan(plan: CareerPlan) { await this.pool.query(`INSERT INTO career_plans (id,owner_id,status,version,direction_codes,target_job_id,target_company_name,target_city,target_salary_text,rationale,updated_at) VALUES ($1,$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11) ON CONFLICT (owner_id,id) DO UPDATE SET status=EXCLUDED.status,version=EXCLUDED.version,direction_codes=EXCLUDED.direction_codes,target_job_id=EXCLUDED.target_job_id,target_company_name=EXCLUDED.target_company_name,target_city=EXCLUDED.target_city,target_salary_text=EXCLUDED.target_salary_text,rationale=EXCLUDED.rationale,updated_at=EXCLUDED.updated_at`, [plan.id, plan.ownerId, plan.status, plan.version, JSON.stringify(plan.directionCodes), plan.targetJobId ?? null, plan.targetCompanyName ?? null, plan.targetCity ?? null, plan.targetSalaryText ?? null, plan.rationale ?? null, plan.updatedAt]); }
  async listJobs(ownerId: string, input: { directionCode?: string; keyword?: string; limit?: number }) { const result = await this.pool.query<TargetJob>(`SELECT id,owner_id AS "ownerId",title,company_name AS "companyName",direction_code AS "directionCode",city,employment_type AS "employmentType",salary_text AS "salaryText",description,requirements,source,created_at::text AS "createdAt" FROM career_target_jobs WHERE owner_id=$1 AND ($2::text IS NULL OR direction_code=$2) AND ($3::text IS NULL OR (title||' '||coalesce(company_name,'')||' '||description) ILIKE '%'||$3||'%') ORDER BY created_at DESC LIMIT $4`, [ownerId, input.directionCode ?? null, input.keyword ?? null, input.limit ?? 20]); return result.rows; }
  async getJob(ownerId: string, jobId: string) { const result = await this.pool.query<TargetJob>(`SELECT id,owner_id AS "ownerId",title,company_name AS "companyName",direction_code AS "directionCode",city,employment_type AS "employmentType",salary_text AS "salaryText",description,requirements,source,created_at::text AS "createdAt" FROM career_target_jobs WHERE owner_id=$1 AND id=$2`, [ownerId, jobId]); return result.rows[0] ?? null; }
  async saveJob(job: TargetJob) { await this.pool.query(`INSERT INTO career_target_jobs (id,owner_id,title,company_name,direction_code,city,employment_type,salary_text,description,requirements,source) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11) ON CONFLICT (owner_id,id) DO UPDATE SET title=EXCLUDED.title,description=EXCLUDED.description,requirements=EXCLUDED.requirements`, [job.id, job.ownerId, job.title, job.companyName ?? null, job.directionCode ?? null, job.city ?? null, job.employmentType, job.salaryText ?? null, job.description, JSON.stringify(job.requirements), job.source]); }
  async saveGap(gap: JobGapAnalysis) { await this.pool.query(`INSERT INTO career_gap_analyses (id,owner_id,job_id,plan_id,match_score,possessed,partial,missing,unknown,evidence_snapshot_at) VALUES ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10)`, [gap.id, gap.ownerId, gap.jobId, gap.planId ?? null, gap.matchScore, JSON.stringify(gap.possessed), JSON.stringify(gap.partial), JSON.stringify(gap.missing), JSON.stringify(gap.unknown), gap.evidenceSnapshotAt]); }
  async getLatestGap(ownerId: string, jobId: string) { const result = await this.pool.query<JobGapAnalysis>(`SELECT id,owner_id AS "ownerId",job_id AS "jobId",plan_id AS "planId",match_score AS "matchScore",possessed,partial,missing,unknown,evidence_snapshot_at::text AS "evidenceSnapshotAt",created_at::text AS "createdAt" FROM career_gap_analyses WHERE owner_id=$1 AND job_id=$2 ORDER BY created_at DESC LIMIT 1`, [ownerId, jobId]); return result.rows[0] ?? null; }
}
