import { randomUUID } from "node:crypto";
import type { CapabilityErrorCode, DomainCommand } from "../../contracts/capability.ts";
import type { CareerApplication } from "./types.ts";
import type { CareerContext, CareerPlan, CreateCareerPlanDraftInput, GetCareerPlanInput, GetTargetJobsInput, SaveTargetJobInput, AnalyzeJobGapInput, SelectTargetJobInput, ConfirmCareerPlanInput, CareerCapabilityResult } from "./contracts.ts";
import type { CareerRepository } from "./repository.ts";
import { emptyCareerJob } from "./repository.ts";

export class CareerService implements CareerApplication {
  private readonly repo: CareerRepository;
  constructor(repo: CareerRepository) { this.repo = repo; }
  async getCareerPlan(ctx: CareerContext, input: GetCareerPlanInput) { return this.repo.getPlan(ctx.ownerId, input.status); }
  async createCareerPlanDraft(command: DomainCommand<CreateCareerPlanDraftInput>): Promise<CareerCapabilityResult<{ plan: CareerPlan }>> {
    const current = await this.repo.getPlan(command.context.ownerId, "draft");
    if (current) return this.result({ plan: current }, "已有职业规划草稿", false, current.id, current.version, "draft_created");
    const now = new Date().toISOString(); const plan: CareerPlan = { id: randomUUID(), ownerId: command.context.ownerId, status: "draft", version: 1, directionCodes: command.payload.directionCodes ?? [], targetJobId: command.payload.targetJobId, targetCompanyName: command.payload.targetCompanyName, targetCity: command.payload.targetCity, targetSalaryText: command.payload.targetSalaryText, rationale: command.payload.userNotes, updatedAt: now }; await this.repo.savePlan(plan); return this.result({ plan }, "职业规划草稿已创建", true, plan.id, plan.version, "draft_created");
  }
  async getTargetJobs(ctx: CareerContext, input: GetTargetJobsInput) { return { items: await this.repo.listJobs(ctx.ownerId, input), nextCursor: null }; }
  async saveTargetJob(command: DomainCommand<SaveTargetJobInput>) { const job = emptyCareerJob(command.context, command.payload); await this.repo.saveJob(job); return this.result({ job }, "目标岗位已保存", true, job.id, undefined, "applied"); }
  async selectTargetJob(command: DomainCommand<SelectTargetJobInput>) { const plan = await this.repo.getPlan(command.context.ownerId); const job = await this.repo.getJob(command.context.ownerId, command.payload.jobId); if (!plan || plan.id !== command.payload.planId) return this.reject("职业规划不存在", "NOT_FOUND"); if (!job) return this.reject("岗位不存在", "NOT_FOUND"); if (plan.version !== command.payload.expectedVersion) return this.reject("职业规划版本已变化", "VERSION_CONFLICT"); const next = { ...plan, targetJobId: job.id, version: plan.version + 1, updatedAt: new Date().toISOString() }; await this.repo.savePlan(next); return this.result({ plan: next, job }, "目标岗位已更新", true, plan.id, next.version, "applied"); }
  async confirmCareerPlan(command: DomainCommand<ConfirmCareerPlanInput>) { const plan = await this.repo.getPlan(command.context.ownerId); if (!plan || plan.id !== command.payload.planId) return this.reject("职业规划不存在", "NOT_FOUND"); if (plan.version !== command.payload.expectedVersion) return this.reject("职业规划版本已变化", "VERSION_CONFLICT"); if (plan.status !== "draft") return this.reject("当前规划不可确认", "INVALID_STATE"); const next = { ...plan, status: "confirmed" as const, version: plan.version + 1, updatedAt: new Date().toISOString() }; await this.repo.savePlan(next); return this.result({ plan: next }, "职业规划已确认", true, next.id, next.version, "applied"); }
  async analyzeJobGap(command: DomainCommand<AnalyzeJobGapInput>) { const job = await this.repo.getJob(command.context.ownerId, command.payload.jobId); if (!job) return this.reject("岗位不存在", "NOT_FOUND"); const gap = { id: randomUUID(), ownerId: command.context.ownerId, jobId: job.id, planId: command.payload.planId, matchScore: null, possessed: [], partial: [], missing: job.requirements.filter(x => x.importance === "required").map(x => x.skillCode), unknown: command.payload.includeUnknown === false ? [] : job.requirements.filter(x => x.importance === "preferred").map(x => x.skillCode), evidenceSnapshotAt: new Date().toISOString(), createdAt: new Date().toISOString() }; await this.repo.saveGap(gap); return this.result({ gap }, "岗位差距分析已保存，当前证据不足以计算匹配分", true, gap.id, undefined, "applied"); }
  async getLatestJobGapAnalysis(ctx: CareerContext, input: { jobId: string }) { return this.repo.getLatestGap(ctx.ownerId, input.jobId); }
  async getCareerDashboard(ctx: CareerContext) { const plan = await this.repo.getPlan(ctx.ownerId); const activeJob = plan?.targetJobId ? await this.repo.getJob(ctx.ownerId, plan.targetJobId) : null; return { plan, activeJob, latestGapAnalysis: activeJob ? await this.repo.getLatestGap(ctx.ownerId, activeJob.id) : null, recommendedActions: [] }; }
  async compareTargetJobs(ctx: CareerContext, input: { leftJobId: string; rightJobId: string }) { const left = await this.repo.getJob(ctx.ownerId, input.leftJobId); const right = await this.repo.getJob(ctx.ownerId, input.rightJobId); if (!left || !right) return this.reject("岗位不存在", "NOT_FOUND"); return this.result({ left, right, commonSkills: [], leftOnlySkills: [], rightOnlySkills: [] }, "已完成岗位对比"); }
  private result<T>(data: T, summary: string, changed = false, entityId?: string, version?: number, status: CareerCapabilityResult["status"] = changed ? "applied" : "read"): CareerCapabilityResult<T> { return { ok: true, changed, domain: "career", status, summary, data, ...(entityId ? { entityId } : {}), ...(version ? { version } : {}) }; }
  private reject(summary: string, code: CapabilityErrorCode): CareerCapabilityResult<never> { return { ok: false, changed: false, domain: "career", status: "rejected", summary, error: { code, message: summary, retryable: false } }; }
}
