import type { Pool } from "pg";
import type { LearningRepository } from "./repository.ts";
import type { LearningFeedback, LearningPlan } from "./contracts.ts";
export class PostgresLearningRepository implements LearningRepository {
  private readonly pool: Pool;
  constructor(pool: Pool) { this.pool = pool; }
  async getPlan(ownerId: string, planId?: string) { const result = await this.pool.query<LearningPlan>(`SELECT id,owner_id AS "ownerId",mode,status,source_profile_version AS "sourceProfileVersion",source_career_plan_version AS "sourceCareerPlanVersion",target_job_id AS "targetJobId",start_date::text AS "startDate",end_date::text AS "endDate",weekly_minutes AS "weeklyMinutes",version,learning_goals AS "learningGoals",sources,updated_at::text AS "updatedAt" FROM learning_plans WHERE owner_id=$1 AND ($2::uuid IS NULL OR id=$2) ORDER BY CASE WHEN status='active' THEN 0 ELSE 1 END,updated_at DESC LIMIT 1`, [ownerId, planId ?? null]); const plan = result.rows[0]; if (!plan) return null; const stages = await this.pool.query(`SELECT id,plan_id AS "planId",stage_order AS "order",title,objective,status,tasks FROM learning_stages WHERE plan_id=$1 ORDER BY stage_order`, [plan.id]); return { ...plan, stages: stages.rows } as LearningPlan; }
  async listPlans(ownerId: string) { const result = await this.pool.query<LearningPlan>(`SELECT id,owner_id AS "ownerId",mode,status,source_profile_version AS "sourceProfileVersion",source_career_plan_version AS "sourceCareerPlanVersion",target_job_id AS "targetJobId",start_date::text AS "startDate",end_date::text AS "endDate",weekly_minutes AS "weeklyMinutes",version,learning_goals AS "learningGoals",sources,updated_at::text AS "updatedAt" FROM learning_plans WHERE owner_id=$1 AND status <> 'archived' ORDER BY updated_at DESC`, [ownerId]); const plans: LearningPlan[] = []; for (const plan of result.rows) { const stages = await this.pool.query(`SELECT id,plan_id AS "planId",stage_order AS "order",title,objective,status,tasks FROM learning_stages WHERE plan_id=$1 ORDER BY stage_order`, [plan.id]); plans.push({ ...plan, stages: stages.rows } as LearningPlan); } return plans; }
  async savePlan(plan: LearningPlan) { await this.pool.query(`INSERT INTO learning_plans (id,owner_id,mode,status,source_profile_version,source_career_plan_version,target_job_id,start_date,end_date,weekly_minutes,version,learning_goals,sources,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13::jsonb,$14) ON CONFLICT (owner_id,id) DO UPDATE SET mode=EXCLUDED.mode,status=EXCLUDED.status,version=EXCLUDED.version,learning_goals=EXCLUDED.learning_goals,sources=EXCLUDED.sources,updated_at=EXCLUDED.updated_at`, [plan.id, plan.ownerId, plan.mode, plan.status, plan.sourceProfileVersion, plan.sourceCareerPlanVersion ?? null, plan.targetJobId ?? null, plan.startDate, plan.endDate, plan.weeklyMinutes, plan.version, JSON.stringify(plan.learningGoals), JSON.stringify(plan.sources ?? []), plan.updatedAt]); for (const stage of plan.stages) await this.pool.query(`INSERT INTO learning_stages (id,plan_id,stage_order,title,objective,status,tasks) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT (plan_id,stage_order) DO UPDATE SET title=EXCLUDED.title,objective=EXCLUDED.objective,status=EXCLUDED.status,tasks=EXCLUDED.tasks`, [stage.id, plan.id, stage.order, stage.title, stage.objective, stage.status, JSON.stringify(stage.tasks)]); }
  async saveFeedback(feedback: LearningFeedback) { await this.pool.query(`INSERT INTO learning_feedback (id,owner_id,plan_id,task_id,difficulty,reason,actual_minutes,available_minutes,confidence_score,note) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`, [feedback.id, feedback.ownerId, feedback.planId, feedback.taskId ?? null, feedback.difficulty, feedback.reason ?? null, feedback.actualMinutes ?? null, feedback.availableMinutes ?? null, feedback.confidenceScore ?? null, feedback.note ?? null]); }
}
