import type { CapabilityErrorCode, DomainCommand } from "../../contracts/capability.ts";
import type { LearningApplication } from "./types.ts";
import type { AdjustPlanInput, CreatePlanInput, FeedbackInput, LearningContext, LearningFeedback, LearningPlan, LearningProgress, LearningResult, LearningTask, UpdateTaskInput } from "./contracts.ts";
import type { LearningRepository } from "./repository.ts";
import { newId, taskById } from "./repository.ts";
export class LearningService implements LearningApplication {
  private readonly repo: LearningRepository;
  constructor(repo: LearningRepository) { this.repo = repo; }
  async getActivePlan(ctx: LearningContext, input: { includeTasks?: boolean }) { const plan = await this.repo.getPlan(ctx.ownerId); if (!plan || input.includeTasks !== false) return plan; return { ...plan, stages: plan.stages.map(stage => ({ ...stage, tasks: [] })) }; }
  async listPlans(ctx: LearningContext) { return (this.repo.listPlans ? await this.repo.listPlans(ctx.ownerId) : []).filter(plan => plan.status === "draft"); }
  async getTodayTasks(ctx: LearningContext, input: { date?: string }) { const plan = await this.repo.getPlan(ctx.ownerId); const date = input.date ?? new Date().toISOString().slice(0, 10); return plan?.stages.flatMap(stage => stage.tasks).filter(task => !task.scheduleDate || task.scheduleDate === date) ?? []; }
  async getLearningProgress(ctx: LearningContext, input: { planId?: string }): Promise<LearningProgress | null> { const plan = await this.repo.getPlan(ctx.ownerId, input.planId); if (!plan) return null; const tasks = plan.stages.flatMap(x => x.tasks); const done = tasks.filter(x => x.status === "completed").length; const stage = plan.stages.find(x => x.tasks.some(task => task.status !== "completed")); const stageTasks = stage?.tasks ?? []; return { planId: plan.id, planVersion: plan.version, totalTasks: tasks.length, completedTasks: done, progressPercent: tasks.length ? Math.round(done / tasks.length * 100) : 0, currentStageId: stage?.id, currentStageProgressPercent: stageTasks.length ? Math.round(stageTasks.filter(x => x.status === "completed").length / stageTasks.length * 100) : undefined }; }
  async createLearningPlan(command: DomainCommand<CreatePlanInput>) { const now = new Date().toISOString(); const plan: LearningPlan = { id: newId(), ownerId: command.context.ownerId, mode: command.payload.mode, status: "draft", sourceProfileVersion: command.payload.sourceProfileVersion, sourceCareerPlanVersion: command.payload.sourceCareerPlanVersion, targetJobId: command.payload.targetJobId, startDate: command.payload.startDate, endDate: command.payload.endDate, weeklyMinutes: command.payload.weeklyMinutes, version: 1, learningGoals: command.payload.learningGoals, stages: command.payload.stages.map((stage, index) => ({ id: newId(), planId: "", order: index + 1, title: stage.title, objective: stage.objective, status: "todo", tasks: stage.tasks.map(task => ({ id: newId(), planId: "", stageId: "", title: task.title, description: task.description, taskType: task.taskType, status: "todo", estimatedMinutes: task.estimatedMinutes, actualMinutes: null, capabilityKey: task.capabilityKey, evidenceRequired: task.evidenceRequired ?? false })) })), updatedAt: now }; plan.stages.forEach(stage => { stage.planId = plan.id; stage.tasks.forEach(task => { task.planId = plan.id; task.stageId = stage.id; }); }); await this.repo.savePlan(plan); return this.result({ plan }, "学习计划草案已保存", true, plan.id, 1); }
  async updateTaskStatus(command: DomainCommand<UpdateTaskInput>) { const plan = await this.repo.getPlan(command.context.ownerId); const task = plan && taskById(plan, command.payload.taskId); if (!plan || !task) return this.reject("任务不存在", "NOT_FOUND"); task.status = command.payload.status; if (command.payload.actualMinutes !== undefined) task.actualMinutes = command.payload.actualMinutes; plan.version++; plan.updatedAt = new Date().toISOString(); await this.repo.savePlan(plan); return this.result({ task }, "学习任务状态已更新", true, task.id, plan.version); }
  async recordLearningFeedback(command: DomainCommand<FeedbackInput>) { const plan = await this.repo.getPlan(command.context.ownerId, command.payload.planId); if (!plan) return this.reject("学习计划不存在", "NOT_FOUND"); const feedback: LearningFeedback = { id: newId(), ownerId: command.context.ownerId, ...command.payload, createdAt: new Date().toISOString() }; await this.repo.saveFeedback(feedback); return this.result({ feedback }, "学习反馈已记录", true, feedback.id, plan.version); }
  async adjustLearningPlan(command: DomainCommand<AdjustPlanInput>) { const plan = await this.repo.getPlan(command.context.ownerId, command.payload.planId); if (!plan) return this.reject("学习计划不存在", "NOT_FOUND"); for (const operation of command.payload.operations) { if (operation.type === "reschedule" && operation.taskId && operation.scheduleDate) { const task = taskById(plan, operation.taskId); if (task) task.scheduleDate = operation.scheduleDate; } if (operation.type === "replace_resource" && operation.taskId && operation.resource) { const task = taskById(plan, operation.taskId); if (task) task.description = operation.resource; } } plan.version++; plan.updatedAt = new Date().toISOString(); await this.repo.savePlan(plan); return this.result({ plan, adjustment: command.payload }, "学习计划已调整", true, plan.id, plan.version); }
  async confirmLearningPlan(command: DomainCommand<{ planId: string; expectedPlanVersion: number; keepUnfinishedTasks?: boolean }>) { const plan = await this.repo.getPlan(command.context.ownerId, command.payload.planId); if (!plan) return this.reject("学习计划不存在", "NOT_FOUND"); if (plan.version !== command.payload.expectedPlanVersion) return this.reject("学习计划版本已变化", "VERSION_CONFLICT"); if (plan.mode !== "trial" || !["draft", "active"].includes(plan.status)) return this.reject("当前计划不可确认", "INVALID_STATE"); plan.mode = "final"; plan.status = "active"; plan.version++; plan.updatedAt = new Date().toISOString(); await this.repo.savePlan(plan); return this.result({ plan }, "学习计划已确认并激活", true, plan.id, plan.version); }
  private result<T>(data: T, summary: string, changed = false, entityId?: string, version?: number): LearningResult<T> { return { ok: true, changed, domain: "learning", status: changed ? "applied" : "read", summary, data, ...(entityId ? { entityId } : {}), ...(version ? { version } : {}) }; }
  private reject(summary: string, code: CapabilityErrorCode): LearningResult<never> { return { ok: false, changed: false, domain: "learning", status: "rejected", summary, error: { code, message: summary, retryable: false } }; }
}
