import test from "node:test";
import assert from "node:assert/strict";
import { EvidenceApplication } from "../src/modules/evidence/application.ts";
import { EvidenceService } from "../src/modules/evidence/service.ts";
import type { EvidenceRepository } from "../src/modules/evidence/repository.ts";

test("应用层写入会委托到仓储并保留业务结果", async () => { const saved: string[] = []; const repo: EvidenceRepository = { createRecord: async r => void saved.push(r.recordId), getRecord: async () => null, listRecords: async () => [], updateRecord: async () => {}, saveAssessment: async () => {}, saveReview: async () => {}, saveInterview: async () => {}, getInterview: async () => null }; const app = new EvidenceApplication(new EvidenceService(), repo); const result = await app.recordLearningEvidence({ ownerId: "owner" }, { kind: "activity", title: "学习", content: "完成练习", occurredAt: "2026-09-13T10:00:00+08:00" }); assert.equal(result.ok, true); assert.equal(saved.length, 1); });
test("应用层面试创建和结束会委托仓储", async () => { let saved = 0; let stored: any = null; const repo: EvidenceRepository = { createRecord: async () => {}, getRecord: async () => null, listRecords: async () => [], updateRecord: async () => {}, saveAssessment: async () => {}, saveReview: async () => {}, saveInterview: async i => { saved++; stored = i; }, getInterview: async () => stored }; const app = new EvidenceApplication(new EvidenceService(), repo); const started = await app.startInterview({ ownerId: "owner" }, { kind: "skills", id: "http" }, 2); assert.equal(started.ok, true); assert.equal(saved, 1); const read = await app.getInterviewSession({ ownerId: "owner" }, started.entityId!); assert.equal(read.ok, true); const ended = await app.finishInterview({ ownerId: "owner" }, started.entityId!); assert.equal(ended.ok, true); assert.equal(saved, 2); });
test("应用层提交回答会持久化回答和反馈", async () => { let answers = 0; const repo: EvidenceRepository = { createRecord: async () => {}, getRecord: async () => null, listRecords: async () => [], updateRecord: async () => {}, saveAssessment: async () => {}, saveReview: async () => {}, saveInterview: async () => {}, getInterview: async () => null, saveAnswer: async () => { answers++; }, saveAnswerFeedback: async () => { answers++; } }; const app = new EvidenceApplication(new EvidenceService(), repo); const started = await app.startInterview({ ownerId: "owner" }, { kind: "skills", id: "http" }, 1); const i = started.data!.interview; const result = await app.submitInterviewAnswer({ ownerId: "owner" }, i.interviewId, i.questions[0].questionId, "回答"); assert.equal(result.ok, true); assert.equal(answers, 2); });
test("应用层面试历史查询委托仓储", async () => { const repo: EvidenceRepository = { createRecord: async () => {}, getRecord: async () => null, listRecords: async () => [], updateRecord: async () => {}, saveAssessment: async () => {}, saveReview: async () => {}, saveInterview: async () => {}, getInterview: async () => null, listInterviews: async () => [] }; const app = new EvidenceApplication(new EvidenceService(), repo); const result = await app.getInterviewRecords({ ownerId: "owner" }); assert.equal(result.ok, true); assert.deepEqual(result.data!.items, []); });
