import test from "node:test";
import assert from "node:assert/strict";
import { EvidenceService } from "../src/modules/evidence/service.ts";
import { createEvidenceCapabilities } from "../src/modules/evidence/capabilities.ts";

test("学习记录支持幂等保存、查询和撤回", () => { const s = new EvidenceService(); const ctx = { ownerId: "owner-a", requestId: "r1" }; const first = s.recordLearningEvidence(ctx, { kind: "activity", title: "活动", content: "内容", occurredAt: "2026-09-13T10:00:00+08:00", skillIds: ["http"] }); const replay = s.recordLearningEvidence(ctx, { kind: "activity", title: "活动", content: "内容", occurredAt: "2026-09-13T10:00:00+08:00", skillIds: ["http"] }); assert.equal(first.entityId, replay.entityId); assert.equal(s.getLearningRecords({ ownerId: "owner-a" }).data?.items.length, 1); s.updateLearningEvidence({ ownerId: "owner-a" }, first.entityId!, { withdraw: "撤回" }); assert.equal(s.getLearningRecords({ ownerId: "owner-a" }).data?.items.length, 0); });
test("模拟面试只接受当前题并防止重复回答", () => { const s = new EvidenceService(); const ctx = { ownerId: "owner-a" }; const started = s.startInterview(ctx, { kind: "skills", id: "http" }, 2); const interview = started.data!.interview; const wrong = s.submitInterviewAnswer(ctx, interview.interviewId, interview.questions[1].questionId, "回答"); assert.equal(wrong.ok, false); const answer = s.submitInterviewAnswer(ctx, interview.interviewId, interview.questions[0].questionId, "回答"); assert.equal(answer.ok, true); const replay = s.submitInterviewAnswer(ctx, interview.interviewId, interview.questions[0].questionId, "回答"); assert.equal(replay.changed, false); });
test("证据评估和阶段复盘只使用当前用户记录", () => { const s = new EvidenceService(); const ctx = { ownerId: "owner-a" }; const saved = s.recordLearningEvidence(ctx, { kind: "project_outcome", title: "项目成果", content: "完成接口", occurredAt: "2026-09-13T10:00:00+08:00", skillIds: ["http"] }); const assessment = s.evaluateLearningEvidence(ctx, [saved.entityId!], ["http"]); assert.equal(assessment.ok, true); const review = s.generateLearningReview(ctx, "2026-09-13T00:00:00+08:00", "2026-09-14T00:00:00+08:00"); assert.equal(review.data!.review.progress.length, 1); assert.equal(s.getLearningReviews(ctx).data!.items.length, 1); });
test("记录和面试按 owner 隔离，空查询不生成数据", () => { const s = new EvidenceService(); const mine = s.recordLearningEvidence({ ownerId: "owner-a" }, { kind: "activity", title: "我的记录", content: "内容", occurredAt: "2026-09-13T10:00:00+08:00" }); assert.equal(s.getLearningRecords({ ownerId: "owner-b" }).data!.items.length, 0); assert.equal(s.getSkillEvidence({ ownerId: "owner-b" }).data!.items.length, 0); assert.equal(s.getInterviewRecords({ ownerId: "owner-b" }).data!.items.length, 0); assert.equal(mine.ok, true); });
test("Capability 在进入 Service 前拒绝非法输入", () => { const tool = createEvidenceCapabilities(new EvidenceService()).find(t => t.name === "submit_interview_answer")!; assert.throws(() => tool.execute({ ownerId: "owner" }, { interviewId: "i", questionId: "q", answer: "" })); });
test("成果修正 Capability 拒绝未知字段和空修正", () => { const tool = createEvidenceCapabilities(new EvidenceService()).find(t => t.name === "update_learning_evidence")!; assert.throws(() => tool.execute({ ownerId: "owner" }, { action: "amend", recordId: "r", changes: {} })); assert.throws(() => tool.execute({ ownerId: "owner" }, { action: "amend", recordId: "r", changes: { unknown: "x" } })); });
test("学习记录查询拒绝反向时间范围", () => { const result = new EvidenceService().getLearningRecords({ ownerId: "owner" }, { from: "2026-09-14T00:00:00+08:00", to: "2026-09-13T00:00:00+08:00" }); assert.equal(result.ok, false); assert.equal(result.error?.code, "INVALID_ARGUMENT"); });
test("学习记录查询支持类型筛选和分页元数据", () => { const s = new EvidenceService(); const ctx = { ownerId: "owner" }; s.recordLearningEvidence(ctx, { kind: "activity", title: "活动", content: "内容", occurredAt: "2026-09-13T10:00:00+08:00" }); s.recordLearningEvidence(ctx, { kind: "project_outcome", title: "成果", content: "内容", occurredAt: "2026-09-13T11:00:00+08:00" }); const result = s.getLearningRecords(ctx, { kind: "project_outcome", limit: 1 }); assert.equal(result.ok, true); assert.equal(result.data?.items.length, 1); assert.equal(result.data?.items[0]?.kind, "project_outcome"); assert.equal(result.data?.page.hasMore, false); });
