import type { Pool } from "pg";
import type { Assessment, Interview, LearningRecord, Review } from "./contracts.ts";
import type { EvidenceRepository } from "./repository.ts";

/** PostgreSQL adapter. Business validation and owner checks remain in EvidenceService. */
export class PostgresEvidenceRepository implements EvidenceRepository {
  constructor(private readonly pool: Pool) {}
  async createRecord(record: LearningRecord) { await this.pool.query(`INSERT INTO ei_records (id,owner_id,kind,status,title,content,occurred_at,duration_minutes,task_id,skill_ids,version,source_domain,source_entity_id,source_revision,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,'evidence',$1,'1',$12,$12)`, [record.recordId, record.ownerId, record.kind, record.status, record.title, record.content, record.occurredAt, record.durationMinutes, record.taskId ?? null, JSON.stringify(record.skillIds ?? []), record.version, record.createdAt]); }
  async getRecord(ownerId: string, recordId: string) { const r = await this.pool.query<LearningRecord>(`SELECT id AS "recordId",owner_id AS "ownerId",kind,status,title,content,occurred_at AS "occurredAt",duration_minutes AS "durationMinutes",task_id AS "taskId",skill_ids AS "skillIds",version,created_at AS "createdAt",updated_at AS "updatedAt" FROM ei_records WHERE owner_id=$1 AND id=$2`, [ownerId, recordId]); return r.rows[0] ?? null; }
  async listRecords(ownerId: string, filter: { from?: string; to?: string; taskId?: string; skillId?: string }) { const values: unknown[] = [ownerId]; const where = ["owner_id=$1", "status='active'"]; if (filter.from) { values.push(filter.from); where.push(`occurred_at >= $${values.length}`); } if (filter.to) { values.push(filter.to); where.push(`occurred_at < $${values.length}`); } if (filter.taskId) { values.push(filter.taskId); where.push(`task_id = $${values.length}`); } if (filter.skillId) { values.push(filter.skillId); where.push(`skill_ids ? $${values.length}`); } const r = await this.pool.query<LearningRecord>(`SELECT id AS "recordId",owner_id AS "ownerId",kind,status,title,content,occurred_at AS "occurredAt",duration_minutes AS "durationMinutes",task_id AS "taskId",skill_ids AS "skillIds",version,created_at AS "createdAt",updated_at AS "updatedAt" FROM ei_records WHERE ${where.join(" AND ")} ORDER BY occurred_at DESC,id DESC`, values); return r.rows; }
  async updateRecord(record: LearningRecord) { await this.pool.query(`UPDATE ei_records SET status=$3,title=$4,content=$5,occurred_at=$6,duration_minutes=$7,task_id=$8,skill_ids=$9::jsonb,version=$10,updated_at=$11 WHERE owner_id=$1 AND id=$2`, [record.ownerId, record.recordId, record.status, record.title, record.content, record.occurredAt, record.durationMinutes, record.taskId ?? null, JSON.stringify(record.skillIds ?? []), record.version, record.updatedAt]); }
  async saveAssessment(assessment: Assessment) { await this.pool.query(`INSERT INTO ei_assessments (id,owner_id,evidence_ids,skill_ids,status,findings,operation_key) VALUES ($1,$2,$3::jsonb,$4::jsonb,$5,$6::jsonb,$7) ON CONFLICT (owner_id,id) DO UPDATE SET status=EXCLUDED.status,findings=EXCLUDED.findings`, [assessment.assessmentId, assessment.ownerId, JSON.stringify(assessment.evidenceIds), JSON.stringify(assessment.skillIds), assessment.status, JSON.stringify(assessment.findings), assessment.assessmentId]); }
  async saveReview(review: Review) { await this.pool.query(`INSERT INTO ei_reviews (id,owner_id,range_from,range_to,time_zone,status,result,operation_key) VALUES ($1,$2,$3,$4,'UTC',$5,$6::jsonb,$7) ON CONFLICT (owner_id,id) DO UPDATE SET status=EXCLUDED.status,result=EXCLUDED.result`, [review.reviewId, review.ownerId, review.from, review.to, review.status, JSON.stringify(review), review.reviewId]); }
  async saveInterview(interview: Interview) { await this.pool.query(`INSERT INTO ei_interviews (id,owner_id,target,status,total_questions,answered_count,version,operation_key) VALUES ($1,$2,$3::jsonb,$4,$5,$6,1,$7) ON CONFLICT (owner_id,id) DO UPDATE SET status=EXCLUDED.status,answered_count=EXCLUDED.answered_count,version=EXCLUDED.version`, [interview.interviewId, interview.ownerId, JSON.stringify(interview.target), interview.status, interview.totalQuestions, interview.answeredCount, interview.interviewId]); }
  async getInterview(ownerId: string, interviewId: string) { const r = await this.pool.query(`SELECT id AS "interviewId",owner_id AS "ownerId",target,status,total_questions AS "totalQuestions",answered_count AS "answeredCount",version FROM ei_interviews WHERE owner_id=$1 AND id=$2`, [ownerId, interviewId]); return r.rows[0] ? { ...r.rows[0], questions: [], answers: [] } as Interview : null; }
}
