import { randomUUID } from "node:crypto";
import { recordInputSchema, type EvidenceContext, type LearningRecord, type RecordInput, type Interview, type CapabilityResult, type SkillEvidence, type Review, type Assessment } from "./contracts.ts";

export class EvidenceService {
  private records = new Map<string, LearningRecord>();
  private interviews = new Map<string, Interview>();
  private reviews = new Map<string, Review>();
  private assessments = new Map<string, Assessment>();
  private operations = new Map<string, string>();
  private now() { return new Date().toISOString(); }
  hydrateRecord(record: LearningRecord) { this.records.set(record.recordId, record); }
  discardUnsavedRecord(recordId: string) {
    this.records.delete(recordId);
    for (const [key, id] of this.operations) if (id === recordId) this.operations.delete(key);
  }
  hydrateInterview(interview: Interview) { this.interviews.set(interview.interviewId, interview); }
  private result<T>(data: T, summary: string, changed = false, entityId?: string): CapabilityResult<T> { return { ok: true, changed, domain: "evidence", entityId, status: changed ? "applied" : "read", summary, data }; }
  private duplicate<T>(ctx: EvidenceContext, data: T, entityId?: string): CapabilityResult<T> { return { ...this.result(data, "重复请求，返回已有结果"), data, entityId }; }
  recordLearningEvidence(ctx: EvidenceContext, input: RecordInput): CapabilityResult<{ record: LearningRecord }> {
    const parsed = recordInputSchema.parse(input); const key = ctx.requestId ? `${ctx.ownerId}:record:${ctx.requestId}` : undefined;
    if (key && this.operations.has(key)) { const id = this.operations.get(key)!; return this.duplicate(ctx, { record: this.records.get(id)! }, id); }
    const now = this.now(); const record: LearningRecord = { ...parsed, durationMinutes: parsed.durationMinutes ?? null, skillIds: parsed.skillIds ?? [], recordId: randomUUID(), ownerId: ctx.ownerId, version: 1, status: "active", createdAt: now, updatedAt: now };
    this.records.set(record.recordId, record); if (key) this.operations.set(key, record.recordId); return this.result({ record }, "学习记录已保存", true, record.recordId);
  }
  getLearningRecords(ctx: EvidenceContext, filter: { from?: string; to?: string; taskId?: string; skillId?: string } = {}) {
    const items = [...this.records.values()].filter(r => r.ownerId === ctx.ownerId && r.status === "active").filter(r => !filter.taskId || r.taskId === filter.taskId).filter(r => !filter.skillId || r.skillIds?.includes(filter.skillId)).filter(r => !filter.from || r.occurredAt >= filter.from!).filter(r => !filter.to || r.occurredAt < filter.to!); return this.result({ items }, "已读取学习记录");
  }
  updateLearningEvidence(ctx: EvidenceContext, recordId: string, changes: Partial<RecordInput> | { withdraw: string }): CapabilityResult<{ record: LearningRecord }> {
    const record = this.records.get(recordId); if (!record || record.ownerId !== ctx.ownerId) return { ok: false, changed: false, domain: "evidence", status: "rejected", summary: "记录不存在", error: { code: "NOT_FOUND", message: "记录不存在" } };
    if ("withdraw" in changes) record.status = "withdrawn"; else Object.assign(record, recordInputSchema.partial().parse(changes)); record.version++; record.updatedAt = this.now(); return this.result({ record }, "学习记录已更新", true, recordId);
  }
  getSkillEvidence(ctx: EvidenceContext, skillId?: string): CapabilityResult<{ items: SkillEvidence[] }> { const groups = new Map<string, string[]>(); for (const r of this.records.values()) if (r.ownerId === ctx.ownerId && r.status === "active") for (const s of r.skillIds ?? []) if (!skillId || s === skillId) groups.set(s, [...(groups.get(s) ?? []), r.recordId]); const items = [...groups].map(([id, ids]) => ({ skillId: id, support: ids.length > 1 ? "supported" : "partial", rationale: "基于已保存的学习成果，仍需结合具体材料验证", recordIds: ids } as SkillEvidence)); return this.result({ items }, "已读取能力证据"); }
  evaluateLearningEvidence(ctx: EvidenceContext, evidenceIds: string[], skillIds: string[]): CapabilityResult<{ assessment: Assessment }> { const records = [...this.records.values()].filter(r => r.ownerId === ctx.ownerId && r.status === "active" && evidenceIds.includes(r.recordId)); const assessment: Assessment = { assessmentId: randomUUID(), ownerId: ctx.ownerId, evidenceIds, skillIds, status: "succeeded", findings: skillIds.map(skillId => ({ skillId, support: records.some(r => r.skillIds?.includes(skillId)) ? "partial" : "insufficient", rationale: records.length ? "基于已保存记录，材料和实际表现仍需进一步验证" : "没有可用证据", recordIds: records.map(r => r.recordId) } as SkillEvidence)), createdAt: this.now() }; this.assessments.set(assessment.assessmentId, assessment); return this.result({ assessment }, "能力证据评估已保存", true, assessment.assessmentId); }
  generateLearningReview(ctx: EvidenceContext, from: string, to: string): CapabilityResult<{ review: Review }> { const records = [...this.records.values()].filter(r => r.ownerId === ctx.ownerId && r.status === "active" && r.occurredAt >= from && r.occurredAt < to); const review: Review = { reviewId: randomUUID(), ownerId: ctx.ownerId, from, to, status: "succeeded", progress: records.map(r => r.title), blockers: records.filter(r => /卡|难|问题/.test(r.content)).map(r => r.content), suggestions: records.length ? ["继续补充成果材料并验证关联能力"] : ["先记录一次真实学习活动"], createdAt: this.now() }; this.reviews.set(review.reviewId, review); return this.result({ review }, "阶段复盘已生成", true, review.reviewId); }
  getLearningReviews(ctx: EvidenceContext) { return this.result({ items: [...this.reviews.values()].filter(r => r.ownerId === ctx.ownerId) }, "已读取阶段复盘"); }
  startInterview(ctx: EvidenceContext, target: Interview["target"], totalQuestions = 3): CapabilityResult<{ interview: Interview }> { const interview: Interview = { interviewId: randomUUID(), ownerId: ctx.ownerId, target, status: "active", totalQuestions, answeredCount: 0, questions: Array.from({ length: totalQuestions }, (_, i) => ({ questionId: randomUUID(), ordinal: i + 1, prompt: `请说明与训练范围相关的一个具体实践（第 ${i + 1} 题）。` })), answers: [] }; this.interviews.set(interview.interviewId, interview); return this.result({ interview }, "模拟面试已开始", true, interview.interviewId); }
  getInterviewSession(ctx: EvidenceContext, interviewId: string) { const i = this.interviews.get(interviewId); if (!i || i.ownerId !== ctx.ownerId) return { ok: false, changed: false, domain: "evidence", status: "rejected", summary: "面试不存在", error: { code: "NOT_FOUND", message: "面试不存在" } } as CapabilityResult<never>; return this.result({ interview: i }, "已读取面试会话"); }
  submitInterviewAnswer(ctx: EvidenceContext, interviewId: string, questionId: string, text: string) { const i = this.interviews.get(interviewId); if (!i || i.ownerId !== ctx.ownerId) return this.getInterviewSession(ctx, interviewId); if (i.status !== "active") return { ok: false, changed: false, domain: "evidence", status: "rejected", summary: "面试已结束", error: { code: "INVALID_STATE", message: "面试已结束" } } as CapabilityResult<never>; const existing = i.answers.find(a => a.questionId === questionId); if (existing) return this.result({ answer: existing, interview: i }, "重复提交，返回已有回答"); if (!text.trim()) return { ok: false, changed: false, domain: "evidence", status: "rejected", summary: "回答不能为空", error: { code: "INVALID_ARGUMENT", message: "回答不能为空" } } as CapabilityResult<never>; const q = i.questions.find(q => q.questionId === questionId); if (!q || q.ordinal !== i.answeredCount + 1) return { ok: false, changed: false, domain: "evidence", status: "rejected", summary: "不是当前题目", error: { code: "INVALID_STATE", message: "不是当前题目" } } as CapabilityResult<never>; const answer = { answerId: randomUUID(), questionId, text: text.trim(), feedback: "反馈占位：将基于回答内容生成具体建议" }; i.answers.push(answer); i.answeredCount++; if (i.answeredCount === i.totalQuestions) i.status = "completed"; return this.result({ answer, interview: i }, "回答已保存", true, answer.answerId); }
  finishInterview(ctx: EvidenceContext, interviewId: string) { const i = this.interviews.get(interviewId); if (!i || i.ownerId !== ctx.ownerId) return this.getInterviewSession(ctx, interviewId); if (i.status === "active") i.status = "ended_early"; return this.result({ interview: i }, "模拟面试已结束", true, interviewId); }
  getInterviewFeedback(ctx: EvidenceContext, interviewId: string) { const i = this.interviews.get(interviewId); if (!i || i.ownerId !== ctx.ownerId) return this.getInterviewSession(ctx, interviewId); return this.result({ interviewId, status: i.status, answeredCount: i.answeredCount, feedback: i.answers.map(a => ({ answerId: a.answerId, feedback: a.feedback })) }, "已读取面试反馈"); }
  getInterviewRecords(ctx: EvidenceContext) { const owned = [...this.interviews.values()].filter(i => i.ownerId === ctx.ownerId); return this.result({ items: owned.map(i => ({ interviewId: i.interviewId, status: i.status, answeredCount: i.answeredCount, totalQuestions: i.totalQuestions, target: i.target })), session: owned.find(i => i.status === "active") ?? null }, "已读取面试历史"); }
}
